[build]
  command = "npm run build"
  publish = "dist"

# Handle all client-side routing including nested routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Specific redirect for document routes
[[redirects]]
  from = "/documents/*"
  to = "/index.html"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "18"

# Enable SPA mode and optimize for single page application
[build.processing]
  skip_processing = false
[build.processing.html]
  pretty_urls = true

# Additional headers for SPA routing
[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"